### ISSUE TITLE
upload to Maven Central

### ISSUE THREAD

**Issue by egonw** [cdk/cdk-scaffold#10]
@johnmay, the next step here would be to upload to Maven Central.

Can you plz check (perhaps after the CDK 2.9 release) if you are happy with the groupID/artifactID combination? If so, we can push it there too.

**Comment by johnmay** [comment]
All looks OK to me

**Comment by egonw** [comment]
Okay, the `SNAPSHOT` is online! :)

https://s01.oss.sonatype.org/content/repositories/snapshots/org/openscience/cdk/cdk-scaffold/2.8-SNAPSHOT/
