### ISSUE TITLE
JavaDoc not available

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk-scaffold#14]
In the readme, there is a link that is supposed to be pointing to the online version of the latest JavaDoc for this package: http://cdk.github.io/cdk-scaffold/latest/docs/api/index.html?overview-summary.html 

But it is not working. Is the JavaDoc going to be automatically built and published (by SonarCloud?) once we do the first proper release or do we need to take some action here?

**Comment by johnmay** [comment]
This repo needs an orphan gh-pages and then the doc placed there. Or just remove the link, IDE's give you the JavaDoc anyways.

**Comment by JonasSchaub** [comment]
Hi @johnmay 

I have set up the orphan gh-pages branch and put the doc for version 2.8-SNAPSHOT there (for now): [http://cdk.github.io/cdk-scaffold/2.8-SNAPSHOT/docs/api/index.html?overview-summary.html](http://cdk.github.io/cdk-scaffold/2.8-SNAPSHOT/docs/api/index.html?overview-summary.html)

I just can't figure out how to set the "/latest/" pointer. Could you help me with that?

**Comment by johnmay** [comment]
Oh it's just a symbolic link. 
```
$ ln -s 2.8-SNAPSHOT latest
```

**Comment by JonasSchaub** [comment]
Thanks, it's working now!

(my basic "mistake" was that I'm working on a Windows machine...)
