### ISSUE TITLE
release CDK Scaffold 2.8 and then start 2.9 development?

### ISSUE THREAD

**Issue by egonw** [cdk/cdk-scaffold#15]
@JonasSchaub, okay, I think this is now ready for the "CDK 2.8"-based release, right?

And then we open development and use CDK 2.9?

**Comment by JonasSchaub** [comment]
@egonw , on my side, everything would be ready for a proper release, yes!
Can/should I do something there?

**Comment by egonw** [comment]
Okay, I'll make a release.

**Comment by JonasSchaub** [comment]
Thank you!

**Comment by egonw** [comment]
Done: https://zenodo.org/record/8336038
