### ISSUE TITLE
Set up release archiving on Zenodo

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk-scaffold#2]

**Comment by JonasSchaub** [comment]
And add CITATION.cff

**Comment by egonw** [comment]
> And add CITATION.cff

Before the release, as Zenodo will use that info. See https://github.com/cdk/cdk-scaffold/issues/6

**Comment by egonw** [comment]
I turned on the Zenodo archiving option. You should now be able to make archives.
