### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk-scaffold#4]

**Comment by egonw** [comment]
@JonasSchaub, we have SonarCloud now. Seems all green!

**Comment by JonasSchaub** [comment]
@egonw that is great, thanks! 
Sorry, I was occupied with a lot of other things in the past weeks (my PhD defence is on Wednesday). 
In the week after, I will look into the SonarCloud report and fix some of the complaints (e.g. the two bugs that it found).

**Comment by egonw** [comment]
> my PhD defence is on Wednesday

Ah, good luck!

**Comment by JonasSchaub** [comment]
@egonw thank you!
